version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookit_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookit_network

  backend:
    build: ./backend
    container_name: bookit_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bookit
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bookit_network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: bookit_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - bookit_network
    command: npm run dev

networks:
  bookit_network:
    driver: bridge

volumes:
  postgres_data: